apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: kube-prometheus-stack
  
  source:
    helm:
      version: v3
      valueFiles:
      - values-bwb-dev.yaml
    path: helm-charts/kube-prometheus-stack
    repoURL: https://github.com/paas2/prometheus 
    targetRevision: HEAD
    
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:  
      prune: true 
